:PROPERTIES:
:ID:       b0de2636-c7ba-4707-94b9-f5402a5a96e6
:END:
#+title: AKTE Nalatenschap bijzondere erfenis
#+filetags: :concept:
#+OPTIONS: toc:nil

* Kennisgeving aan de Erfgenamen

Thans zijn voor mij verschenen de erflaters van de Bakkerij, welke mij, Notaris Van de Kruimels, opdracht hebben gegeven de erfgenamen bijeen te brengen teneinde een bijzondere nalatenschap af te wikkelen.
Uit de aan mij overgelegde stukken blijkt dat de erflater niet heeft gekozen voor een gebruikelijke verdeling van zijn bezittingen.

Integendeel.

Bij uiterste wilsbeschikking heeft de erflater bepaald dat slechts diegene die in staat blijkt de nagelaten aanwijzingen te doorgronden, aanspraak kan maken op de inhoud van de nalatenschap.

Documenten lijken doelbewust verspreid en voorzien van obscure informatie.
Hetgeen op het eerste gezicht eenvoudig oogt, verdient mogelijk nadere bestudering.

Mij is opgedragen u, als mogelijk erfgenaam, toegang te verschaffen tot de beschikbare stukken.

Wat zich achter deze nalatenschap bevindt is mij bekend, doch niet aan mij om prijs te geven.

De waarheid dient door de erfgenamen zelf te worden gevonden.

Moge uw onderzoek zorgvuldig zijn en uw oordeel scherp.

* Samenvatting

Onderzoek de beschikbare akten.

Vind hetgeen de erflater verborgen heeft gehouden.

Bij succesvolle afronding zult u een vlag aantreffen in de vorm:

#+begin_example
flag{voorbeeld_van_een_vlag}
#+end_example

* Contact

Middels deze kennisgeving wordt aan alle belanghebbenden, erfgenamen, vermoedelijke erfgenamen en overige bij de nalatenschap betrokken personen medegedeeld dat Notaris Van de Kruimels met ingang van 19 september beschikbaar zal zijn voor het beantwoorden van vragen met betrekking tot de onderhavige nalatenschap.

Degenen die nadere toelichting wensen omtrent de archiefstukken, bewijsstukken, aktes of overige geregistreerde bescheiden worden verzocht zich te vervoegen in het IRC-kanaal #notaris, alwaar de notaris gedurende de afwikkeling van deze zaak zitting zal houden.

De notaris behoudt zich uitdrukkelijk het recht voor vragen te beantwoorden, ontwijkend te beantwoorden, dan wel uitsluitend een spoor van kruimels achter te laten.

Aldus vastgesteld,

Notaris Van de Kruimels

Bewaarder der Archieven,
Toezichthouder op de Nalatenschap,
Tijdelijk belast met vragen die aanzienlijk eenvoudiger hadden kunnen


* Eerste Mededeling van de Notaris

Een goed archief vertelt nooit het volledige verhaal.

Een uitstekend archief vertelt zelfs nauwelijks iets.

Soms bevindt relevante informatie zich niet in het document zelf, maar in hetgeen tussen de regels werd achtergelaten.


* Vereiste Eigenschappen van een Bekwaam Erfgenaam

Bij de afwikkeling van deze nalatenschap kunnen de volgende vaardigheden van nut blijken:

- Nauwkeurige observatie;
- Vermogen tot logisch redeneren;
- Onderzoek van digitale documenten;
- Kennis van gegevensformaten en omzettingen;
- Nieuwsgierigheid;
- Doorzettingsvermogen.

* Aanwijzingen

Aanwijzingen kunnen beschikbaar worden gesteld.

De notaris merkt echter op dat iedere ontvangen aanwijzing onvermijdelijk afbreuk doet aan de persoonlijke eer die men aan een zelfstandige oplossing zou kunnen ontlenen.

* Vorm van de Nalatenschap

Wanneer alle benodigde aanwijzingen correct zijn samengebracht, zal een vlag zichtbaar worden.

Bijvoorbeeld:

#+begin_example
flag{f4m1l13_d4g_2026}
#+end_example

De erflater heeft daarbij aangetekend dat niet iedere boodschap zich in algemeen Nederlands of Engels zal presenteren.

Soms verdient een alternatieve schrijfwijze nadere aandacht.

* Reglement

- Het toepassen van brute-force technieken wordt afgeraden tenzij expliciet toegestaan;
- Wanneer een oplossing zich onmiddellijk lijkt aan te dienen, verdient extra voorzichtigheid aanbeveling;
- Bespreek uw bevindingen bij voorkeur nadat de nalatenschap volledig is afgewikkeld;
- Volg de kruimels waar deze u ook mogen brengen.
- Voor het maken van recepten is het verstandig een [[https://cyberchef.org/][cyberchef]] te raadplegen.

* Slotverklaring

Aldus opgemaakt en vastgelegd door,

Notaris Van de Kruimels

Bewaarder der Archieven,
Toezichthouder op de Nalatenschap,
Volger van de Kruimels.

"De waarheid laat zelden brood achter, maar vrijwel altijd kruimels."
